### ISSUE TITLE
Definir estrutura do banco de dados

### ISSUE THREAD

**Issue by visued** [visued/Analise-Sentimentos-Ecommerce#1]
Os dados serão extraidos do Magazine Luiza, Casas Bahia e Ponto frio.

Nome do site  -> Código
Nome da Pessoa
Data
Rating
Like e dislike
Texto do comentário

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Definir estrutura do banco de dados](https://trello.com/c/wqg9XgM3/27-definir-estrutura-do-banco-de-dados)

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Definir estrutura do banco de dados](https://trello.com/c/7vwY87Qf/37-definir-estrutura-do-banco-de-dados)

**Comment by visued** [comment]
![Estrutura do Banco](https://user-images.githubusercontent.com/5278800/108611135-4f829000-73ba-11eb-8697-3b75778b56d9.png)

**Comment by visued** [comment]
![Screenshot_2021-02-20  Untitled DbDesigner net](https://user-images.githubusercontent.com/5278800/108611502-e13fcc80-73bd-11eb-9955-549fe77823ce.png)
