### ISSUE TITLE
Preparar ambiente para desenvolvimento (Definir tecnologias)

### ISSUE THREAD

**Issue by visued** [visued/Analise-Sentimentos-Ecommerce#10]

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Preparar ambiente para desenvolvimento (Definir tecnologias)](https://trello.com/c/joZ1glZr/28-preparar-ambiente-para-desenvolvimento-definir-tecnologias)

**Comment by visued** [comment]
IDE: Vscode
Linguagem de Programação: Python 3.9.2
Bibliotecas Instaladas: Scrapy e SQLAlchemy
