### ISSUE TITLE
Sprint 01 - Definir Tema

### ISSUE THREAD

**Issue by mateusbrodrigues** [visued/Analise-Sentimentos-Ecommerce#11]
A finalidade de um e-commerce é permitir que o consumidor faça compras de forma rápida e segura, sem a necessidade de se deslocar até uma loja física.
No Brasil, segue em expansão, no mês de dezembro de 2020, registraram alta de 53,83%, em relação ao mesmo tempo em 2019, os dados são do índice MCC-ENET. 
Segundo dados do ReclameAqui, plataforma utilizada para reclamações contra empresas, produtos e serviços, na Black Friday de 2020 houve um total de 140.164 reclamações. O volume é 15,5% maior do que o registrado na edição de 2019 (Dados computados até dia 31 de janeiro). O índice geral de solução por parte das empresas  também cresceu, ficou em 77,2%.
Observando o crescimento desse mercado, iremos auxiliar o consumidor a encontrar quais os melhores produtos.

Referência: https://noticias.reclameaqui.com.br/noticias/black-friday-2020-encerra-com-mais-de-140-mil-reclamacoes-e_4119/

**Comment by mateus090** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tema](https://trello.com/c/4CvvDVzy/2-tema)

**Comment by mateus090** [comment]
Tema definido: Análise de sentimentos em comentários de sites e-commerce brasileiros.

**Comment by visued** [comment]
Documentação

**Comment by visued** [comment]
Documentação

**Comment by dfpires** [comment]
identificamos a necessidade de saber identificar

**Comment by dfpires** [comment]
estatística de insatisfação na compra de produto

**Comment by dfpires** [comment]
isso não é importante: dessa forma iremos utilizar os comentários realizados por pessoas que já o adquiriram para tentar identificar qual é o sentimento do consumidor após realizar a compra do produto desejado.
