### ISSUE TITLE
Sprint 01 - Definir motivação

### ISSUE THREAD

**Issue by mateusbrodrigues** [visued/Analise-Sentimentos-Ecommerce#12]
Os comentários dos produtos em lojas de ecommerce contêm informações valiosas que apoiam na tomada de decisões na aquisição de um produto. A motivação deste trabalho está em demonstrar através da análise de sentimentos o quão capaz ela é de influenciar o consumidor no momento da compra.

**Comment by mateus090** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Motivação](https://trello.com/c/IQZCjvLh/3-motiva%C3%A7%C3%A3o)
