### ISSUE TITLE
Sprint 01 -  Definir problema de pesquisa

### ISSUE THREAD

**Issue by mateusbrodrigues** [visued/Analise-Sentimentos-Ecommerce#13]
Como as técnicas de análise de sentimentos e de engenharia de software possibilitam entender os sentimentos dos consumidores de plataforma e-commerce?

**Comment by mateus090** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Problema de Pesquisa](https://trello.com/c/6wRm7ssC/4-problema-de-pesquisa)

**Comment by dfpires** [comment]
Como as técnicas de ES possibilitam entender os sentimentos dos compradores?
