### ISSUE TITLE
Sprint 01 - Definir justificativa

### ISSUE THREAD

**Issue by mateusbrodrigues** [visued/Analise-Sentimentos-Ecommerce#14]
A análise visa oferecer  baseando-se nos comentários de pessoas que já adquiriram o produto, qual o sentimento e/ou satisfação em adquirir tal produto, dessa forma queremos expor esses dados a partir de relatórios para que possa ajudar outras pessoas a identificar produtos bons e de qualidade e ajudar o consumidor na tomada de decisão na hora da compra de um produto, podendo ser em loja física ou e-commerce.

**Comment by mateus090** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Justificativa](https://trello.com/c/l0RX4oo1/6-justificativa)
