### ISSUE TITLE
Sprint 01 -  Definir objetivos

### ISSUE THREAD

**Issue by mateusbrodrigues** [visued/Analise-Sentimentos-Ecommerce#15]
Será feito uma entrevista via Google Forms para validar o projeto. Faremos a coleta dos dados que serão armazenados em um banco de dados para posteriormente aplicar técnicas de análise de sentimentos. Por fim, disponibilizaremos um relatório que possa apoiar os clientes no momento da compra de um produto.

**Comment by mateus090** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Objetivos](https://trello.com/c/d6ya0Pgz/7-objetivos)

**Comment by dfpires** [comment]
O objetivo deste trabalho é aplicar técnicas de coleta de dados em comentários de sites de ecommerce brasileiros e popular um banco de dados. Com isso, será feito a análise de sentimentos destes comentários para disponibilizar um relatório que possa apoiar os clientes no momento da compra de um produto.

**Comment by dfpires** [comment]
objetivos específicos ...... entrevistar, analisar, modelar, implementar
