### ISSUE TITLE
Sprint 01 - Definir procedimentos metodológicos

### ISSUE THREAD

**Issue by mateusbrodrigues** [visued/Analise-Sentimentos-Ecommerce#16]
Neste projeto, serão utilizadas metodologias de software para facilitar o gerenciamento do projeto, tais como o caso de uso, matriz de rastreabilidade, EAP,BPMN,TAP, Diagramas como o de atividade, sequência e máquina de estado. 
Além disso, aplicaremos o conceito de Gerenciamento de configuração de software(GCS), a fim de garantir que tenhamos um alto padrão de qualidade no projeto.
No desenvolvimento, utilizaremos tecnologias que são referências no mercado, como as linguagens R e Python. Para o banco de dados, utilizaremos o PostgreSQL. Todas estas tecnologias foram utilizadas nas disciplinas durante o curso.

**Comment by mateus090** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Procedimentos Metodológicos](https://trello.com/c/KRO2dT5U/5-procedimentos-metodol%C3%B3gicos)
