### ISSUE TITLE
Definir termos de pesquisa (nome dos produtos)

### ISSUE THREAD

**Issue by visued** [visued/Analise-Sentimentos-Ecommerce#2]

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Definir termos de pesquisa (nome dos produtos)](https://trello.com/c/FP24vRqs/36-definir-termos-de-pesquisa-nome-dos-produtos)

**Comment by visued** [comment]
Ponto Frio 
Eletrodomestico - https://www.pontofrio.com.br/c/eletrodomesticos/?filtro=c13&faixapreco=0to43833&nid=201449
Smartphone - https://www.pontofrio.com.br/c/telefones-e-celulares/smartphones/?filtro=c38_c326&nid=111259
SmartTV - https://www.pontofrio.com.br/c/tv-e-video/televisores/smart-tv/?filtro=c1_c2_c1588&nid=111239

Casas Bahia
Eletrodomestico - https://www.casasbahia.com.br/c/eletrodomesticos/?filtro=c13&faixapreco=0to43833&nid=201449
Smartphone - https://www.casasbahia.com.br/c/telefones-e-celulares/smartphones/?Filtro=c38_c326&nid=111259
SmartTV - https://www.casasbahia.com.br/c/tv-e-video/televisores/smart-tv/?filtro=c1_c2_c1588&nid=201450

Magazine Luiza
Eletrodomestico - https://www.magazineluiza.com.br/eletrodomesticos/l/ed?page=1
Smartphone - https://www.magazineluiza.com.br/smartphone/celulares-e-smartphones/s/te/tcsp?page=1
SmartTV - https://www.magazineluiza.com.br/smart-tv/tv-e-video/s/et/elit?page=1
