### ISSUE TITLE
Acessar o site e pesquisar o produto usando termos de pesquisa - Casas Bahia

### ISSUE THREAD

**Issue by mateusbrodrigues** [visued/Analise-Sentimentos-Ecommerce#27]
A finalidade de um e-commerce é permitir que o consumidor faça compras de forma rápida e segura, sem a necessidade de se deslocar até uma loja física.
No Brasil, segue em expansão, no mês de dezembro de 2020, registraram alta de 53,83%, em relação ao mesmo tempo em 2019, os dados são do índice MCC-ENET.
Observando o crescimento desse mercado identificamos a necessidade de saber identificar quais os melhores produtos a se encontrar em meio a milhares, dessa forma iremos utilizar os comentários realizados por pessoas que já o adquiriram para tentar identificar qual é o sentimento do consumidor após realizar a compra do produto desejado.

**Comment by mateus090** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Acessar o site e pesquisar o produto usando termos de pesquisa - Casas Bahia](https://trello.com/c/6IwyQmeF/39-acessar-o-site-e-pesquisar-o-produto-usando-termos-de-pesquisa-casas-bahia)
