### ISSUE TITLE
Acessar o site e pesquisar o produto usando termos de pesquisa - Magazine Luiza

### ISSUE THREAD

**Issue by visued** [visued/Analise-Sentimentos-Ecommerce#3]

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Acessar o site e pesquisar o produto usando termos de pesquisa](https://trello.com/c/3QMAg84L/35-acessar-o-site-e-pesquisar-o-produto-usando-termos-de-pesquisa)

**Comment by mateusbrodrigues** [comment]
Obs: utilizar 'pages' retornada no json para paginação.
