### ISSUE TITLE
Extrair da página o código do produto para ser utilizado nas chamadas GET

### ISSUE THREAD

**Issue by visued** [visued/Analise-Sentimentos-Ecommerce#4]

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Extrair da página o código do produto para ser utilizado nas chamadas GET](https://trello.com/c/b9vzHOeb/34-extrair-da-p%C3%A1gina-o-c%C3%B3digo-do-produto-para-ser-utilizado-nas-chamadas-get)
