### ISSUE TITLE
Criar lógica para verificar quantidade de reviews e quantidade de páginas

### ISSUE THREAD

**Issue by visued** [visued/Analise-Sentimentos-Ecommerce#5]

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Criar lógica para verificar quantidade de reviews e quantidade de páginas](https://trello.com/c/yR3eVAiK/33-criar-l%C3%B3gica-para-verificar-quantidade-de-reviews-e-quantidade-de-p%C3%A1ginas)
