### ISSUE TITLE
Marcar Call com professor Geraldo para definir técnicas para analise.

### ISSUE THREAD

**Issue by visued** [visued/Analise-Sentimentos-Ecommerce#8]

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Marcar Call com professor Geraldo para definir técnicas para analise](https://trello.com/c/FbrgkStO/30-marcar-call-com-professor-geraldo-para-definir-t%C3%A9cnicas-para-analise)
