### ISSUE TITLE
Documentação (Verificar com Daniel)

### ISSUE THREAD

**Issue by visued** [visued/Analise-Sentimentos-Ecommerce#9]

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [teste](https://trello.com/c/SbhUeREE/1-teste)

**Comment by mateusbrodrigues** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentação (Verificar com Daniel)](https://trello.com/c/rkaVCKhA/29-documenta%C3%A7%C3%A3o-verificar-com-daniel)
